# Generated by Django 5.0.6 on 2024-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('scheduler', 'Scheduler'), ('subscriber', 'Subscriber')], default='subscriber', max_length=10),
        ),
    ]
