# Generated by Django 5.0.6 on 2024-05-25 13:10

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('interval', models.CharField(choices=[('5min', 'Five Minutes'), ('15min', 'Fifteen Minutes'), ('30min', 'Thirty Minutes'), ('1h', 'One Hour'), ('2h', 'Two Hours'), ('4h', 'Four Hours'), ('8h', 'Eight Hours'), ('24h', 'Twenty Four Hours')], max_length=10)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('latest_response', models.TextField(blank=True, null=True)),
                ('last_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_strategy', models.CharField(blank=True, choices=[('class_selector', 'Extracts elements with a specific CSS class using BeautifulSoup.'), ('json_script', 'Parses JSON from a <script> tag and extracts specific data.')], max_length=50, null=True)),
                ('additional_params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
