# Generated by Django 5.0.6 on 2024-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('interval', models.CharField(choices=[('5min', 'Five Minutes'), ('15min', 'Fifteen Minutes'), ('30min', 'Thirty Minutes'), ('1h', 'One Hour'), ('2h', 'Two Hours'), ('4h', 'Four Hours'), ('8h', 'Eight Hours'), ('24h', 'Twenty Four Hours')], max_length=10)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
