# Generated by Django 5.0.6 on 2024-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='latest_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
