# Generated by Django 5.0.6 on 2024-05-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notificationemailaddress_user'),
        ('watcher', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='communication_channel',
        ),
        migrations.AddField(
            model_name='subscription',
            name='notification_email_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.notificationemailaddress'),
        ),
    ]
