# Generated by Django 5.0.6 on 2024-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_scheduledtask_latest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='processing_strategy',
            field=models.CharField(blank=True, choices=[('class_selector', 'Class Selector'), ('json_script', 'Json Script')], max_length=50, null=True),
        ),
    ]
