# Generated by Django 5.0.6 on 2024-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_remove_subscription_communication_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
