# Generated by Django 5.0.6 on 2024-05-21 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_scheduledtask_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='additional_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
