# Generated by Django 5.0.6 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_scheduledtask_additional_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='processing_strategy',
            field=models.CharField(blank=True, choices=[('class_selector', 'Extracts elements with a specific CSS class using BeautifulSoup.'), ('json_script', 'Parses JSON from a <script> tag and extracts specific data.')], max_length=50, null=True),
        ),
    ]
