# Generated by Django 5.0.6 on 2024-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_scheduledtask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
