# Generated by Django 5.0.6 on 2024-05-23 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_scheduledtask_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
