# Generated by Django 5.0.6 on 2024-05-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_notificationemailaddress'),
        ('watcher', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPartial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notificationemailaddress')),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.scheduledtask')),
            ],
        ),
    ]
